# Generated by Django 5.0.1 on 2024-04-15 18:19

from django.db import migrations
from _core.data.cursoBackup import cursoBackupList
from django.core.exceptions import ObjectDoesNotExist


def create_backup_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Curso = apps.get_model('cursos', 'Curso')
    UserCurso = apps.get_model('user_curso', 'UserCurso')

    for entry in cursoBackupList:
        users = entry.pop("users")
        entry.pop("id")
        entry["validade"] = 0
        curso, created = Curso.objects.get_or_create(**entry)
        curso.save()
        for userID in users:
            try:
                user = User.objects.get(pk=userID)
                userCurso = UserCurso.objects.create(user=user, curso=curso)
                userCurso.save()
            except ObjectDoesNotExist:
                ...


class Migration(migrations.Migration):

    dependencies = [
        ('user_curso', '0002_usercurso_certificado'),
        ('cursos', '0003_curso_validade'),
        ('users', '0006_user_cursos')

    ]

    operations = [
        migrations.RunPython(create_backup_data),
    ]
